version: '3'


services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/logs:/var/log/nginx
        - ./:/var/www/html
    expose:
        - "80"
    ports:
      - 8010:80
#    restart: always
    depends_on:
        - php
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
      - ./docker/php/config/custom.ini:/usr/local/etc/php/7.3/conf.d/custom.ini
      - ./docker/php/crontab:/etc/cron.d/myCrontab
  mongo:
      image: mongo:4.0.0
      volumes:
        - ./docker/mongo/data/db:/data/db
        - ./occupancy/data/:/data
      expose:
        - 27017
      ports:
        - "127.0.0.1:27017:27017"
      command: mongod
      restart: always
      depends_on:
        - php


  mysql:
      build:
        context: ./docker/mysql
        dockerfile: Dockerfile
      restart: always
      environment:
          - MYSQL_DATABASE=logic
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=alireza
          - MYSQL_PASSWORD=alireza
      expose:
          - "3306"
      ports:
        - 3306:3306
      volumes:
        - ./docker/mysql/db:/var/lib/mysql
#        - vol-share:/v-share/


   ## --------------------------------------------
      ## | 5 : PhpMyAdmin
      ## --------------------------------------------
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
          - mysql
        expose:
          - '80'
          - '443'
        ports:
          - "8006:80"
        environment:
          - PMA_HOST=mysql
        volumes:
          - /sessions
#           - vol-share:/v-share/